# Generated by Django 2.1.4 on 2018-12-12 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20181211_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='classes.Classroom'),
        ),
    ]
